// Canonical admin emails — single source of truth for frontend gates.
// Rules copies are generated by scripts/sync-admin-allowlist.mjs (marker blocks).
// Functions secret ADMIN_EMAILS must match (comma-separated).
export const ADMIN_EMAILS = [
  'sankalp.eduteam@gmail.com',
  'aeisankalp@gmail.com',
  'mrharisankar78@gmail.com',
  'aromalk035@gmail.com',
  'goureesankarb434@gmail.com',
  'abhishek.rj296@gmail.com',
  'aeiintern.ma01@gmail.com',
];

export const isAdminEmail = (email) =>
  ADMIN_EMAILS.includes(String(email || '').trim().toLowerCase());
